export const dynamic='force-dynamic'; export const revalidate=0;
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteFooter,SiteHeader} from '@/components/site-header';
import {ManagementNav} from '@/components/manage/manage-nav';
import {requireAccount} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {PlayerAvatar} from '@/components/identity';
import {ConfirmSubmitButton} from '@/components/manage/confirm-submit-button';
import {ImageCropField} from '@/components/media/image-crop-field';
import {deletePlayer,removeEntityImage,updatePlayerContacts,updatePlayerIdentity,uploadEntityImage} from '../../registry/actions';

export default async function PlayerRegistryDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const account=await requireAccount(); const {id:identifier}=await params; const sp=await searchParams; const error=typeof sp.error==='string'?sp.error:null; const ok=typeof sp.ok==='string'?sp.ok:null; const supabase=await createClient();
 const isUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(identifier);
 const playerLookup=isUuid
   ?supabase.from('players').select('*').eq('id',identifier).maybeSingle()
   :supabase.from('players').select('*').eq('slug',decodeURIComponent(identifier).toLowerCase()).maybeSingle();
 const {data:player}=await playerLookup; if(!player)notFound();
 const id=player.id; const routeKey=player.slug||id;
 const [membersRes,contactsRes,adminRes,contactManageRes]=await Promise.all([supabase.from('team_memberships').select('id,team_id,start_on,end_on,status,is_primary,shirt_number,team:teams(id,name,club:clubs(name))').eq('player_id',id).order('start_on',{ascending:false}),supabase.from('player_contacts').select('contact_type,value_original,value_normalized,is_whatsapp,notification_consent,verified_at').eq('player_id',id),supabase.rpc('ips_can_admin_player',{p_player_id:id}),supabase.rpc('ips_can_manage_player_contact',{p_player_id:id})]);
 const contacts=contactsRes.data??[]; const email=contacts.find((c:any)=>c.contact_type==='EMAIL') as any; const phone=contacts.find((c:any)=>c.contact_type==='PHONE') as any; const canAdmin=!!adminRes.data; const canManageContact=!!contactManageRes.data; const canGlobalDelete=account.grants.some(g=>(g.role==='OWNER'&&g.scope_type==='GLOBAL')||(g.role==='ADMIN'&&g.scope_type==='GLOBAL'));
 const claim=(await supabase.rpc('ips_registry_players',{p_query:player.ips_code})).data?.find((p:any)=>p.id===id);
 return <main className="shell sports-shell"><SiteHeader/><ManagementNav account={account} active="players"/><section className="entity-command-header player-command"><div className="entity-brand"><PlayerAvatar name={player.display_name} imageUrl={player.profile_image_url} large/><div><Link className="back-link" href="/manage/players">← Player Registry</Link><span className="eyebrow">{player.ips_code}</span><h1>{player.display_name}</h1><p>{player.primary_role||'Player'} · Permanent IPS identity</p></div></div><div className="header-actions">{canAdmin&&<a href="#player-identity" className="button-secondary">Edit player</a>}{!canAdmin&&canManageContact&&<a href="#player-contact" className="button-secondary">Edit roster details</a>}{canGlobalDelete&&<form action={deletePlayer}><input type="hidden" name="player_id" value={id}/><ConfirmSubmitButton className="danger-link" message={`Delete ${player.display_name} (${player.ips_code})? This permanently removes the player identity, roster memberships and private contacts. Players already used in tournament or match history are protected and cannot be deleted.`}>Delete player</ConfirmSubmitButton></form>}<div className={`account-state ${claim?.has_account?'claimed':''}`}><span>ACCOUNT</span><strong>{claim?.has_account?'CLAIMED':'NOT CLAIMED'}</strong><small>Email/phone can link the account later</small></div></div></section>
 {(error||ok)&&<div className={`ops-message ${error?'error':'success'}`}>{error||ok}</div>}
 <section className="ops-kpi-strip"><article><span>IPS ID</span><strong className="small-strong">{player.ips_code}</strong><small>never changes</small></article><article><span>Memberships</span><strong>{membersRes.data?.length??0}</strong><small>career history</small></article><article><span>Email</span><strong>{email?'YES':'—'}</strong><small>private login identifier</small></article><article><span>Phone</span><strong>{phone?'YES':'—'}</strong><small>secondary identifier</small></article></section>
 <section className="entity-layout player-detail-layout"><div className="management-stack"><section className="management-surface"><div className="surface-head"><div><span className="eyebrow">TEAM HISTORY</span><h2>Memberships</h2></div></div><div className="membership-history">{(membersRes.data??[]).map((m:any)=><article key={m.id}><div><strong>{(m.team as any)?.name}</strong><span>{(m.team as any)?.club?.name}</span></div><div><b>{m.status}</b><small>{m.start_on} → {m.end_on||'Present'}{m.shirt_number!=null?` · #${m.shirt_number}`:''}</small></div></article>)}</div></section>
 <section id="player-contact" className="management-surface"><div className="surface-head"><div><span className="eyebrow">PRIVATE CONTACT</span><h2>Account identifiers</h2></div><span>Never public</span></div>{canManageContact?<><form action={updatePlayerContacts} className="compact-form"><input type="hidden" name="player_id" value={id}/><input type="hidden" name="return_to" value={`/manage/players/${routeKey}`}/><label><span>Email</span><input name="email" type="email" defaultValue={email?.value_normalized??''} placeholder="player@example.com"/></label><label><span>Phone / WhatsApp</span><input name="phone" type="tel" defaultValue={phone?.value_normalized??''} placeholder="+393451234567"/></label><label className="consent-check"><input name="whatsapp_consent" type="checkbox" defaultChecked={!!phone?.notification_consent}/><span><b>WhatsApp updates allowed</b><small>Consent record only. Messaging integration comes later.</small></span></label><button>Save private contacts</button></form><div className="privacy-note">Team-scoped managers may update roster contact details only for players on their assigned team. The permanent cricket identity remains <b>{player.ips_code}</b>.</div></>:<div className="privacy-note">You do not have permission to edit this player's private roster contact.</div>}</section></div>
 <aside className="management-stack">{canAdmin&&<><section className="management-surface"><div className="surface-head"><div><span className="eyebrow">OFFICIAL PORTRAIT</span><h2>Profile photo</h2></div><span>Admin only</span></div><div className="portrait-admin"><PlayerAvatar name={player.display_name} imageUrl={player.profile_image_url} large/><div><p>Players cannot upload, replace or remove this image. Upload only the final photo approved for IPS.</p><form action={uploadEntityImage} className="media-form" encType="multipart/form-data"><input type="hidden" name="kind" value="players"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/players/${routeKey}`}/><ImageCropField name="image" label="Choose player photo" aspect="portrait" required initialUrl={player.profile_image_url}/><button>Upload / replace</button></form>{player.profile_image_url&&<form action={removeEntityImage}><input type="hidden" name="kind" value="players"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/players/${routeKey}`}/><button className="danger-link">Remove official photo</button></form>}</div></div></section>
 <section id="player-identity" className="management-surface"><div className="surface-head"><div><span className="eyebrow">PERMANENT DETAILS</span><h2>Player identity</h2></div><span>Admin controlled</span></div><form action={updatePlayerIdentity} className="compact-form"><input type="hidden" name="player_id" value={id}/><input type="hidden" name="return_to" value={`/manage/players/${routeKey}`}/><label><span>Display name</span><input name="display_name" defaultValue={player.display_name}/></label><div className="form-split"><label><span>Given name</span><input name="given_name" defaultValue={player.given_name??''}/></label><label><span>Family name</span><input name="family_name" defaultValue={player.family_name??''}/></label></div><label><span>Primary role</span><input name="primary_role" defaultValue={player.primary_role??''}/></label><label><span>Batting style</span><input name="batting_style" defaultValue={player.batting_style??''}/></label><label><span>Bowling style</span><input name="bowling_style" defaultValue={player.bowling_style??''}/></label><button>Save player details</button></form></section></>}
 {!canAdmin&&<section className="management-surface locked-panel"><span className="eyebrow">IDENTITY PROTECTED</span><h2>Admin-controlled profile</h2><p>You can manage this player's team membership and private roster contact where authorised, but permanent identity details and the official portrait are controlled by IPS administrators.</p></section>}</aside></section><SiteFooter/></main>;
}
