export const dynamic='force-dynamic'; export const revalidate=0;
import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {SiteFooter,SiteHeader} from '@/components/site-header';
import {ManagementNav} from '@/components/manage/manage-nav';
import {requireAccount} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {PlayerAvatar} from '@/components/identity';
import {addExistingPlayer,createPlayerForTeam} from '../../../../registry/actions';

export default async function AddPlayerPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const account=await requireAccount(); const {id}=await params; const sp=await searchParams; const q=typeof sp.q==='string'?sp.q.trim():''; const error=typeof sp.error==='string'?sp.error:null; const supabase=await createClient(); const [{data:team},{data:canManage}]=await Promise.all([supabase.from('teams').select('id,name,club:clubs(name)').eq('id',id).maybeSingle(),supabase.rpc('ips_can_manage_team',{p_team_id:id})]); if(!team)notFound(); if(!canManage)redirect('/manage/teams?error='+encodeURIComponent('You can only add or edit players for teams assigned to your account.'));
 let results:any[]=[]; if(q.length>=2){const r=await supabase.rpc('ips_registry_player_search',{p_team_id:id,p_query:q}); if(!r.error)results=r.data??[];}
 return <main className="shell sports-shell"><SiteHeader/><ManagementNav account={account} active="teams"/><section className="manage-titlebar compact"><div><Link className="back-link" href={`/manage/teams/${id}`}>← {team.name}</Link><span className="eyebrow">ADD PLAYER</span><h1>Search before creating</h1><p>Search IPS first by name, permanent IPS ID, exact email or international phone number. This prevents duplicate cricket careers.</p></div></section>{error&&<div className="ops-message error">{error}</div>}
 <section className="player-add-workspace"><div className="management-surface player-search-panel"><div className="surface-head"><div><span className="eyebrow">STEP 1</span><h2>Find an existing player</h2></div></div><form method="get" className="registry-search"><input name="q" defaultValue={q} placeholder="Name, ITA-0001847, email or +39 phone"/><button>Search IPS</button></form>{q&&<div className="search-result-stack">{results.map(p=><article className="player-search-result" key={p.id}><PlayerAvatar name={p.display_name} imageUrl={p.profile_image_url}/><div><span>{p.matched_by}</span><h3>{p.display_name}</h3><p>{p.ips_code} · {p.primary_role||'Player'}{p.current_team_name?` · ${p.current_team_name}`:' · Unattached'}</p></div>{p.is_on_target_team?<b className="already-chip">Already on team</b>:<form action={addExistingPlayer}><input type="hidden" name="team_id" value={id}/><input type="hidden" name="player_id" value={p.id}/><input name="shirt_number" type="number" min="0" max="999" placeholder="Shirt #"/><button>Add existing →</button></form>}</article>)}{!results.length&&<div className="search-empty"><strong>No matching IPS player.</strong><p>If you have checked the name and contact details, create a new permanent player identity below.</p></div>}</div>}</div>
 <div className="management-surface new-player-panel"><div className="surface-head"><div><span className="eyebrow">STEP 2 · ONLY IF NEW</span><h2>Create player</h2></div><span>Added to {team.name}</span></div><form action={createPlayerForTeam} className="professional-form embedded"><input type="hidden" name="team_id" value={id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}/players/add`}/><div className="form-block flat"><div className="form-split"><label><span>Full / display name *</span><input name="display_name" required placeholder="D. Fernando"/></label><label><span>Shirt number</span><input name="shirt_number" type="number" min="0" max="999" placeholder="18"/></label></div><div className="form-split"><label><span>Given name</span><input name="given_name"/></label><label><span>Family name</span><input name="family_name"/></label></div><div className="form-split"><label><span>Primary role</span><select name="primary_role" defaultValue=""><option value="">Player</option><option>Batter</option><option>Bowler</option><option>All-rounder</option><option>Wicketkeeper</option><option>Wicketkeeper-batter</option></select></label><label><span>Batting style</span><select name="batting_style" defaultValue=""><option value="">Not set</option><option>Right-hand bat</option><option>Left-hand bat</option></select></label></div><label><span>Bowling style</span><input name="bowling_style" placeholder="Right-arm medium / Left-arm spin / etc."/></label></div><div className="form-block contact-block"><div className="form-block-head"><span>↳</span><div><strong>Optional account/contact identifiers</strong><small>Private. These do not replace the permanent IPS player ID.</small></div></div><div className="form-split"><label><span>Email</span><input name="email" type="email" placeholder="player@example.com"/></label><label><span>Phone / WhatsApp</span><input name="phone" type="tel" placeholder="+393451234567"/><small className="field-note">Use international format. Stored as a secondary login/search identifier.</small></label></div><label className="consent-check"><input type="checkbox" name="whatsapp_consent"/><span><b>WhatsApp updates allowed</b><small>Record consent now; actual WhatsApp messaging is not enabled yet.</small></span></label></div><div className="registry-identity-note"><b>IPS creates the permanent identity automatically.</b><span>UUID + public ITA-xxxxxxx code. Email and phone can change later without splitting the player's career.</span></div><button className="button-primary">Create player & add to team →</button></form></div></section><SiteFooter/></main>;
}
