export const dynamic='force-dynamic'; export const revalidate=0;
import Link from 'next/link';
import {SiteFooter,SiteHeader} from '@/components/site-header';
import {ManagementNav} from '@/components/manage/manage-nav';
import {requireAccount,hasManagementRole} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {canCreateVenue} from '@/lib/project4';
import {createVenue} from './actions';
export default async function VenuesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const account=await requireAccount();if(!hasManagementRole(account))return null;const sp=await searchParams;const error=typeof sp.error==='string'?sp.error:null;const ok=typeof sp.ok==='string'?sp.ok:null;const supabase=await createClient();const[{data:venues},{data:cities}]=await Promise.all([supabase.from('venues').select('*').order('name'),supabase.from('cities').select('id,name,code').eq('status','ACTIVE').order('name')]);const cityMap=new Map((cities??[]).map((c:any)=>[c.id,c]));return <main className="shell sports-shell"><SiteHeader/><ManagementNav account={account} active="venues"/><section className="ops-hero compact"><div><span className="eyebrow">PROJECT 4 · VENUES</span><h1>Grounds & venues.</h1><p>Fixtures reference one canonical venue record. The scorer should never retype the ground name.</p></div><div className="ops-summary-card"><span>VENUES</span><strong>{venues?.length??0}</strong><small>canonical grounds</small><Link href="/manage/tournaments">← Tournaments</Link></div></section>{(error||ok)&&<div className={`ops-message ${error?'error':'success'}`}>{error||ok}</div>}<section className="ops-layout"><div className="ops-main"><div className="ops-list">{(venues??[]).map((v:any)=><article key={v.id}><div><span>{cityMap.get(v.city_id)?.name??'Italy'}</span><strong>{v.name}</strong><small>{v.address_text||'Address not set'}</small></div><b>{v.status}</b></article>)}</div></div><aside className="ops-side-card"><span className="eyebrow light">NEW VENUE</span><h2>Add ground</h2>{canCreateVenue(account)?<form action={createVenue} className="ops-form"><label><span>City</span><select name="city_id">{(cities??[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Name</span><input name="name" required placeholder="Napoli Cricket Ground"/></label><label><span>Slug</span><input name="slug" required placeholder="napoli-cricket-ground"/></label><label><span>Address</span><input name="address_text" placeholder="Street / facility"/></label><div className="form-split"><label><span>Latitude</span><input name="latitude" type="number" step="any"/></label><label><span>Longitude</span><input name="longitude" type="number" step="any"/></label></div><button className="button-primary">Create venue</button></form>:<p className="ops-help">Your current role cannot create venues.</p>}</aside></section><SiteFooter/></main>}
