-- IPS Project 7.2 — expand factory PRISM graphics with real data-driven scenes.

begin;

create or replace function public.ips_prism_factory_document_v2(p_key text)
returns jsonb
language plpgsql immutable
as $$
begin
case p_key

when 'vs.fullscreen' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Match VS","designTokens":{"accent":"#19d18f"},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"vs-bg","name":"Cinematic Background","type":"RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":115,"stops":[{"offset":0,"color":"#071622"},{"offset":0.48,"color":"#0b2b3d"},{"offset":1,"color":"#050b12"}]},"noise":0.12}},
{"id":"vs-rings","name":"Energy Depth","type":"EFFECT","zIndex":2,"transform":{"x":460,"y":80,"width":1000,"height":920},"style":{},"effect":{"kind":"ENERGY_RINGS","params":{"count":5,"color":"#19d18f","secondary":"#ce2b37","opacity":0.25}},"animation":{"enterPreset":"IMPACT","durationMs":900,"exitPreset":"FADE","exitDurationMs":350}},
{"id":"vs-tournament","name":"Tournament","type":"TEXT","zIndex":4,"transform":{"x":360,"y":112,"width":1200,"height":50},"style":{"fill":{"type":"SOLID","color":"#8fe0c2"}},"text":{"value":"IPS","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":26,"lineHeight":1,"letterSpacing":4,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"match.tournament.name","fallback":"IPS CRICKET","format":"UPPER","prefix":"","suffix":""}],"animation":{"enterPreset":"FADE","durationMs":450,"delayMs":100,"exitPreset":"FADE","exitDurationMs":220}},
{"id":"vs-home-logo","name":"Team A Logo","type":"IMAGE","zIndex":5,"transform":{"x":230,"y":260,"width":330,"height":330},"style":{},"asset":{"url":"","fit":"CONTAIN","objectPosition":"50% 50%"},"bindings":[{"property":"asset.url","path":"match.home_team.logo_url","fallback":"","format":"IMAGE_URL","prefix":"","suffix":""}],"animation":{"enterPreset":"SLIDE_RIGHT","durationMs":650,"delayMs":220,"exitPreset":"SLIDE_RIGHT","exitDurationMs":320}},
{"id":"vs-home","name":"Team A","type":"TEXT","zIndex":6,"transform":{"x":120,"y":625,"width":550,"height":120},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"HOME TEAM","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":62,"lineHeight":0.95,"letterSpacing":-2,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"match.home_team.name","fallback":"HOME TEAM","format":"UPPER","prefix":"","suffix":""}],"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":560,"delayMs":340,"exitPreset":"FADE","exitDurationMs":250}},
{"id":"vs-away-logo","name":"Team B Logo","type":"IMAGE","zIndex":5,"transform":{"x":1360,"y":260,"width":330,"height":330},"style":{},"asset":{"url":"","fit":"CONTAIN","objectPosition":"50% 50%"},"bindings":[{"property":"asset.url","path":"match.away_team.logo_url","fallback":"","format":"IMAGE_URL","prefix":"","suffix":""}],"animation":{"enterPreset":"SLIDE_LEFT","durationMs":650,"delayMs":220,"exitPreset":"SLIDE_LEFT","exitDurationMs":320}},
{"id":"vs-away","name":"Team B","type":"TEXT","zIndex":6,"transform":{"x":1250,"y":625,"width":550,"height":120},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"AWAY TEAM","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":62,"lineHeight":0.95,"letterSpacing":-2,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"match.away_team.name","fallback":"AWAY TEAM","format":"UPPER","prefix":"","suffix":""}],"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":560,"delayMs":340,"exitPreset":"FADE","exitDurationMs":250}},
{"id":"vs-mark","name":"VS Impact","type":"TEXT","zIndex":8,"transform":{"x":760,"y":330,"width":400,"height":300},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":90,"stops":[{"offset":0,"color":"#ffffff"},{"offset":1,"color":"#19d18f"}]},"glow":18},"text":{"value":"VS","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":220,"lineHeight":0.85,"letterSpacing":-14,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"animation":{"enterPreset":"IMPACT","durationMs":500,"delayMs":470,"exitPreset":"SCALE_POP","exitDurationMs":280}},
{"id":"vs-info","name":"Match Info","type":"TEXT","zIndex":7,"transform":{"x":460,"y":820,"width":1000,"height":72},"style":{"fill":{"type":"SOLID","color":"#a9bdc6"}},"text":{"value":"MATCH","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":28,"lineHeight":1,"letterSpacing":1,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"match.code","fallback":"IPS MATCH","format":"UPPER","prefix":"","suffix":""}]},
{"id":"vs-venue","name":"Venue","type":"TEXT","zIndex":7,"transform":{"x":460,"y":892,"width":1000,"height":44},"style":{"fill":{"type":"SOLID","color":"#67828f"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":750,"fontSize":20,"lineHeight":1,"letterSpacing":1,"align":"CENTER","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"match.venue","fallback":"","format":"UPPER","prefix":"","suffix":""}]},
{"id":"vs-sweep","name":"Final Light Sweep","type":"EFFECT","zIndex":10,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{},"effect":{"kind":"LIGHT_SWEEP","params":{"width":280,"intensity":0.45,"angle":-18}},"animation":{"enterPreset":"LIGHT_SWEEP","durationMs":1200,"delayMs":560,"exitPreset":"FADE","exitDurationMs":100}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"vs","variant":"fullscreen"}}
$json$::jsonb;

when 'batter-info.large' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Batter Info","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"bi-base","name":"Card Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":100,"y":520,"width":920,"height":410},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#071724"},{"offset":1,"color":"#103448"}]},"stroke":{"type":"SOLID","color":"rgba(255,255,255,.15)"},"strokeWidth":1,"corners":{"tl":24,"tr":24,"br":24,"bl":24,"linked":true},"shadows":[{"x":0,"y":24,"blur":70,"spread":0,"color":"rgba(0,0,0,.45)"}]},"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":500,"exitPreset":"WIPE","exitDurationMs":320}},
{"id":"bi-photo","name":"Batter Photo","type":"IMAGE","zIndex":3,"transform":{"x":120,"y":390,"width":330,"height":520},"style":{},"asset":{"url":"","fit":"CONTAIN","objectPosition":"50% 100%"},"bindings":[{"property":"asset.url","path":"current.striker.photo_url","fallback":"","format":"IMAGE_URL","prefix":"","suffix":""}],"animation":{"enterPreset":"SLIDE_UP","durationMs":520,"delayMs":120,"exitPreset":"FADE","exitDurationMs":250}},
{"id":"bi-kicker","name":"Kicker","type":"TEXT","zIndex":4,"transform":{"x":485,"y":560,"width":470,"height":38},"style":{"fill":{"type":"SOLID","color":"#19d18f"}},"text":{"value":"CURRENT BATTER","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":17,"lineHeight":1,"letterSpacing":2.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"bi-name","name":"Batter Name","type":"TEXT","zIndex":4,"transform":{"x":480,"y":610,"width":470,"height":105},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BATTER","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":56,"lineHeight":0.92,"letterSpacing":-2,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.name","fallback":"BATTER","format":"RAW","prefix":"","suffix":""}]},
{"id":"bi-runs","name":"Runs","type":"TEXT","zIndex":4,"transform":{"x":485,"y":745,"width":190,"height":90},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":72,"lineHeight":1,"letterSpacing":-3,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.runs","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"bi-balls","name":"Balls","type":"TEXT","zIndex":4,"transform":{"x":675,"y":765,"width":130,"height":55},"style":{"fill":{"type":"SOLID","color":"#a9bbc4"}},"text":{"value":"0 BALLS","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":21,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.balls","fallback":0,"format":"INTEGER","prefix":"","suffix":" BALLS"}]},
{"id":"bi-boundaries","name":"Boundaries","type":"TEXT","zIndex":4,"transform":{"x":485,"y":842,"width":465,"height":42},"style":{"fill":{"type":"SOLID","color":"#82ddba"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":18,"lineHeight":1,"letterSpacing":1,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.score_display","fallback":"","format":"RAW","prefix":"","suffix":""}]},
{"id":"bi-sweep","name":"Card Sweep","type":"EFFECT","zIndex":8,"transform":{"x":100,"y":520,"width":920,"height":410},"style":{},"effect":{"kind":"LIGHT_SWEEP","params":{"width":180,"intensity":0.28,"angle":-18}},"animation":{"enterPreset":"LIGHT_SWEEP","durationMs":950,"delayMs":240,"exitPreset":"FADE","exitDurationMs":100}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"batter-info","variant":"large"}}
$json$::jsonb;

when 'bowler-info.large' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Bowler Info","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"bo-base","name":"Card Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":900,"y":520,"width":920,"height":410},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":180,"stops":[{"offset":0,"color":"#071724"},{"offset":1,"color":"#103448"}]},"stroke":{"type":"SOLID","color":"rgba(255,255,255,.15)"},"strokeWidth":1,"corners":{"tl":24,"tr":24,"br":24,"bl":24,"linked":true},"shadows":[{"x":0,"y":24,"blur":70,"spread":0,"color":"rgba(0,0,0,.45)"}]},"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":500,"exitPreset":"WIPE","exitDurationMs":320}},
{"id":"bo-photo","name":"Bowler Photo","type":"IMAGE","zIndex":3,"transform":{"x":1480,"y":390,"width":310,"height":520},"style":{},"asset":{"url":"","fit":"CONTAIN","objectPosition":"50% 100%"},"bindings":[{"property":"asset.url","path":"current.bowler.photo_url","fallback":"","format":"IMAGE_URL","prefix":"","suffix":""}],"animation":{"enterPreset":"SLIDE_UP","durationMs":520,"delayMs":120,"exitPreset":"FADE","exitDurationMs":250}},
{"id":"bo-kicker","name":"Kicker","type":"TEXT","zIndex":4,"transform":{"x":955,"y":560,"width":470,"height":38},"style":{"fill":{"type":"SOLID","color":"#19d18f"}},"text":{"value":"CURRENT BOWLER","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":17,"lineHeight":1,"letterSpacing":2.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"bo-name","name":"Bowler Name","type":"TEXT","zIndex":4,"transform":{"x":950,"y":610,"width":500,"height":105},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BOWLER","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":56,"lineHeight":0.92,"letterSpacing":-2,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"current.bowler.name","fallback":"BOWLER","format":"RAW","prefix":"","suffix":""}]},
{"id":"bo-fig","name":"Bowling Figures","type":"TEXT","zIndex":4,"transform":{"x":955,"y":748,"width":300,"height":88},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0/0","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":70,"lineHeight":1,"letterSpacing":-3,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.bowler.figures_display","fallback":"0/0 (0.0)","format":"RAW","prefix":"","suffix":""}]},
{"id":"bo-style","name":"Bowling Style","type":"TEXT","zIndex":4,"transform":{"x":955,"y":845,"width":470,"height":38},"style":{"fill":{"type":"SOLID","color":"#8fdcbe"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":17,"lineHeight":1,"letterSpacing":0.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.bowler.bowling_style","fallback":"","format":"UPPER","prefix":"","suffix":""}]}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"bowler-info","variant":"large"}}
$json$::jsonb;

when 'need-from.lower-third' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Need From","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"nf-base","name":"Situation Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":420,"y":835,"width":1080,"height":145},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#0a2f42"},{"offset":0.55,"color":"#071a29"},{"offset":1,"color":"#0e6a50"}]},"stroke":{"type":"SOLID","color":"rgba(255,255,255,.16)"},"strokeWidth":1,"corners":{"tl":20,"tr":20,"br":20,"bl":20,"linked":true},"shadows":[{"x":0,"y":18,"blur":55,"spread":0,"color":"rgba(0,0,0,.38)"}]},"animation":{"enterPreset":"SLIDE_UP","durationMs":420,"exitPreset":"SLIDE_DOWN","exitDurationMs":300}},
{"id":"nf-label","name":"Situation Label","type":"TEXT","zIndex":3,"transform":{"x":470,"y":858,"width":240,"height":34},"style":{"fill":{"type":"SOLID","color":"#78dab6"}},"text":{"value":"MATCH SITUATION","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":14,"lineHeight":1,"letterSpacing":2,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"nf-main","name":"Need From","type":"TEXT","zIndex":4,"transform":{"x":465,"y":895,"width":820,"height":65},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"NEED 1 FROM 1","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":50,"lineHeight":1,"letterSpacing":-1.8,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.chase_display","fallback":"","format":"UPPER","prefix":"","suffix":""}],"conditions":{"mode":"ALL","conditions":[{"path":"innings.number","operator":"EQ","value":2},{"path":"innings.runs_required","operator":"GT","value":0}]}},
{"id":"nf-rrr","name":"Required Rate","type":"TEXT","zIndex":4,"transform":{"x":1260,"y":868,"width":190,"height":76},"style":{"fill":{"type":"SOLID","color":"#9eb5bf"}},"text":{"value":"RRR 0.00","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":21,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.rrr","fallback":"—","format":"DECIMAL_2","prefix":"RRR ","suffix":""}]}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"need-from","variant":"lower-third"}}
$json$::jsonb;

when 'partnership.lower-third' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Current Partnership","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"cp-base","name":"Partnership Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":520,"y":842,"width":880,"height":132},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#071724"},{"offset":1,"color":"#12384a"}]},"stroke":{"type":"SOLID","color":"rgba(255,255,255,.14)"},"strokeWidth":1,"corners":{"tl":18,"tr":18,"br":18,"bl":18,"linked":true}},"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":400,"exitPreset":"WIPE","exitDurationMs":280}},
{"id":"cp-title","name":"Title","type":"TEXT","zIndex":3,"transform":{"x":565,"y":863,"width":340,"height":30},"style":{"fill":{"type":"SOLID","color":"#79dcb7"}},"text":{"value":"CURRENT PARTNERSHIP","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":14,"lineHeight":1,"letterSpacing":2,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"cp-runs","name":"Partnership Runs","type":"TEXT","zIndex":4,"transform":{"x":560,"y":900,"width":260,"height":58},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0 RUNS","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":42,"lineHeight":1,"letterSpacing":-1.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.partnership.runs","fallback":0,"format":"INTEGER","prefix":"","suffix":" RUNS"}]},
{"id":"cp-balls","name":"Partnership Balls","type":"TEXT","zIndex":4,"transform":{"x":850,"y":900,"width":220,"height":58},"style":{"fill":{"type":"SOLID","color":"#a8bdc6"}},"text":{"value":"0 BALLS","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":26,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.partnership.balls","fallback":0,"format":"INTEGER","prefix":"","suffix":" BALLS"}]},
{"id":"cp-names","name":"Batters","type":"TEXT","zIndex":4,"transform":{"x":1080,"y":870,"width":270,"height":80},"style":{"fill":{"type":"SOLID","color":"#d5e0e4"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":17,"lineHeight":1.15,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.name","fallback":"","format":"RAW","prefix":"","suffix":""}]}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"partnership","variant":"lower-third"}}
$json$::jsonb;

when 'playing-xi.home' then return public.ips_prism_factory_document_v2('playing-xi-base') || jsonb_build_object('name','PRISM Playing XI — Home','metadata',jsonb_build_object('factory','IPS PRISM','scene','playing-xi','variant','home'));
when 'playing-xi.away' then return (
  select jsonb_set(
    jsonb_set(public.ips_prism_factory_document_v2('playing-xi-base'),'{name}','"PRISM Playing XI — Away"'::jsonb),
    '{elements,3,bindings,0,path}','"match.away_team.name"'::jsonb
  )
);

when 'playing-xi-base' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Playing XI","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"xi-bg","name":"Fullscreen Base","type":"RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":120,"stops":[{"offset":0,"color":"#06131e"},{"offset":0.6,"color":"#0b2a3c"},{"offset":1,"color":"#061018"}]},"noise":0.08}},
{"id":"xi-accent","name":"Prism Accent","type":"RECT","zIndex":2,"transform":{"x":90,"y":105,"width":12,"height":865},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":180,"stops":[{"offset":0,"color":"#19d18f"},{"offset":0.5,"color":"#ffffff"},{"offset":1,"color":"#ce2b37"}]}}},
{"id":"xi-title","name":"Title","type":"TEXT","zIndex":3,"transform":{"x":145,"y":105,"width":700,"height":80},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"PLAYING XI","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":62,"lineHeight":1,"letterSpacing":-2.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"xi-team","name":"Team Name","type":"TEXT","zIndex":3,"transform":{"x":145,"y":186,"width":1200,"height":48},"style":{"fill":{"type":"SOLID","color":"#82ddba"}},"text":{"value":"TEAM","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":27,"lineHeight":1,"letterSpacing":2,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"match.home_team.name","fallback":"TEAM","format":"UPPER","prefix":"","suffix":""}]},
{"id":"xi-rows","name":"Player Rows","type":"REPEATER","zIndex":4,"transform":{"x":145,"y":280,"width":1580,"height":650},"style":{},"repeat":{"path":"playing_xi.home","limit":11,"direction":"VERTICAL","gap":4,"itemWidth":1580,"itemHeight":54,"template":[
{"id":"row-bg","name":"Row Background","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1580,"height":54},"style":{"fill":{"type":"SOLID","color":"rgba(255,255,255,.055)"},"corners":{"tl":8,"tr":8,"br":8,"bl":8,"linked":true}}},
{"id":"row-no","name":"Order","type":"TEXT","zIndex":2,"transform":{"x":16,"y":0,"width":60,"height":54},"style":{"fill":{"type":"SOLID","color":"#6ed6af"}},"text":{"value":"1","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":20,"lineHeight":1,"letterSpacing":0,"align":"CENTER","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.order","fallback":"","format":"INTEGER","prefix":"","suffix":""}]},
{"id":"row-name","name":"Player Name","type":"TEXT","zIndex":2,"transform":{"x":95,"y":0,"width":760,"height":54},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"PLAYER","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":24,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.name","fallback":"PLAYER","format":"RAW","prefix":"","suffix":""}]},
{"id":"row-role","name":"Role","type":"TEXT","zIndex":2,"transform":{"x":900,"y":0,"width":560,"height":54},"style":{"fill":{"type":"SOLID","color":"#829aa6"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":18,"lineHeight":1,"letterSpacing":1,"align":"RIGHT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.role","fallback":"","format":"UPPER","prefix":"","suffix":""}]}
]}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"playing-xi","variant":"base"}}
$json$::jsonb;

when 'batting-scorecard.fullscreen' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Live Batting Scorecard","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"bs-bg","name":"Fullscreen Base","type":"RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":110,"stops":[{"offset":0,"color":"#06111b"},{"offset":0.65,"color":"#0b293b"},{"offset":1,"color":"#061018"}]},"noise":0.06}},
{"id":"bs-head","name":"Header","type":"ROUNDED_RECT","zIndex":2,"transform":{"x":90,"y":80,"width":1740,"height":155},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#0e6b50"},{"offset":1,"color":"#0a2638"}]},"corners":{"tl":22,"tr":22,"br":22,"bl":22,"linked":true}}},
{"id":"bs-team","name":"Team","type":"TEXT","zIndex":3,"transform":{"x":135,"y":100,"width":850,"height":55},"style":{"fill":{"type":"SOLID","color":"#c7f4e3"}},"text":{"value":"BATTING TEAM","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":28,"lineHeight":1,"letterSpacing":2,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.batting_team.name","fallback":"BATTING TEAM","format":"UPPER","prefix":"","suffix":""}]},
{"id":"bs-score","name":"Score","type":"TEXT","zIndex":3,"transform":{"x":130,"y":155,"width":540,"height":70},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0/0","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":58,"lineHeight":1,"letterSpacing":-2.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.score_display","fallback":"0/0","format":"RAW","prefix":"","suffix":""}]},
{"id":"bs-meta","name":"Overs CRR","type":"TEXT","zIndex":3,"transform":{"x":1280,"y":140,"width":490,"height":62},"style":{"fill":{"type":"SOLID","color":"#c1d1d8"}},"text":{"value":"OVERS","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":24,"lineHeight":1,"letterSpacing":1,"align":"RIGHT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.overs","fallback":"0.0","format":"RAW","prefix":"OVERS ","suffix":""}]},
{"id":"bs-cols","name":"Columns","type":"TEXT","zIndex":3,"transform":{"x":115,"y":252,"width":1680,"height":44},"style":{"fill":{"type":"SOLID","color":"#688591"}},"text":{"value":"BATTER                                                       R        B        4s       6s       SR","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":15,"lineHeight":1,"letterSpacing":1,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"bs-rows","name":"Batting Rows","type":"REPEATER","zIndex":4,"transform":{"x":110,"y":305,"width":1690,"height":600},"style":{},"repeat":{"path":"batting_scorecard","limit":11,"direction":"VERTICAL","gap":3,"itemWidth":1690,"itemHeight":50,"template":[
{"id":"r-bg","name":"Row Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1690,"height":50},"style":{"fill":{"type":"SOLID","color":"rgba(255,255,255,.045)"},"corners":{"tl":7,"tr":7,"br":7,"bl":7,"linked":true}}},
{"id":"r-name","name":"Batter","type":"TEXT","zIndex":2,"transform":{"x":18,"y":0,"width":750,"height":50},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BATTER","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":21,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.name","fallback":"—","format":"RAW","prefix":"","suffix":""}]},
{"id":"r-runs","name":"Runs","type":"TEXT","zIndex":2,"transform":{"x":820,"y":0,"width":130,"height":50},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":22,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.runs","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"r-balls","name":"Balls","type":"TEXT","zIndex":2,"transform":{"x":980,"y":0,"width":120,"height":50},"style":{"fill":{"type":"SOLID","color":"#a9bbc4"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":19,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.balls","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"r-4","name":"Fours","type":"TEXT","zIndex":2,"transform":{"x":1130,"y":0,"width":105,"height":50},"style":{"fill":{"type":"SOLID","color":"#8da5af"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":18,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.fours","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"r-6","name":"Sixes","type":"TEXT","zIndex":2,"transform":{"x":1260,"y":0,"width":105,"height":50},"style":{"fill":{"type":"SOLID","color":"#8da5af"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":18,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.sixes","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"r-sr","name":"Strike Rate","type":"TEXT","zIndex":2,"transform":{"x":1400,"y":0,"width":245,"height":50},"style":{"fill":{"type":"SOLID","color":"#81dbb9"}},"text":{"value":"0.0","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":19,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.strike_rate","fallback":0,"format":"DECIMAL_1","prefix":"","suffix":""}]}
]}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"batting-scorecard","variant":"fullscreen"}}
$json$::jsonb;

when 'bowling-scorecard.fullscreen' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Live Bowling Scorecard","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"bw-bg","name":"Fullscreen Base","type":"RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":110,"stops":[{"offset":0,"color":"#06111b"},{"offset":0.65,"color":"#0b293b"},{"offset":1,"color":"#061018"}]},"noise":0.06}},
{"id":"bw-head","name":"Header","type":"ROUNDED_RECT","zIndex":2,"transform":{"x":90,"y":110,"width":1740,"height":145},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#123e58"},{"offset":1,"color":"#0b6b50"}]},"corners":{"tl":22,"tr":22,"br":22,"bl":22,"linked":true}}},
{"id":"bw-title","name":"Title","type":"TEXT","zIndex":3,"transform":{"x":135,"y":130,"width":900,"height":58},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BOWLING SCORECARD","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":44,"lineHeight":1,"letterSpacing":-1.4,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"bw-team","name":"Bowling Team","type":"TEXT","zIndex":3,"transform":{"x":135,"y":192,"width":900,"height":36},"style":{"fill":{"type":"SOLID","color":"#9de3c9"}},"text":{"value":"TEAM","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":20,"lineHeight":1,"letterSpacing":1.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"innings.bowling_team.name","fallback":"BOWLING TEAM","format":"UPPER","prefix":"","suffix":""}]},
{"id":"bw-cols","name":"Columns","type":"TEXT","zIndex":3,"transform":{"x":120,"y":285,"width":1660,"height":44},"style":{"fill":{"type":"SOLID","color":"#688591"}},"text":{"value":"BOWLER                                                   O        M        R        W        ECON","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":15,"lineHeight":1,"letterSpacing":1,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"bw-rows","name":"Bowling Rows","type":"REPEATER","zIndex":4,"transform":{"x":115,"y":340,"width":1680,"height":570},"style":{},"repeat":{"path":"bowling_scorecard","limit":10,"direction":"VERTICAL","gap":4,"itemWidth":1680,"itemHeight":58,"template":[
{"id":"rb","name":"Row Base","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1680,"height":58},"style":{"fill":{"type":"SOLID","color":"rgba(255,255,255,.05)"},"corners":{"tl":8,"tr":8,"br":8,"bl":8,"linked":true}}},
{"id":"rn","name":"Bowler","type":"TEXT","zIndex":2,"transform":{"x":18,"y":0,"width":720,"height":58},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BOWLER","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":24,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.name","fallback":"—","format":"RAW","prefix":"","suffix":""}]},
{"id":"ro","name":"Overs","type":"TEXT","zIndex":2,"transform":{"x":790,"y":0,"width":150,"height":58},"style":{"fill":{"type":"SOLID","color":"#c4d2d8"}},"text":{"value":"0.0","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":20,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.overs","fallback":"0.0","format":"RAW","prefix":"","suffix":""}]},
{"id":"rm","name":"Maidens","type":"TEXT","zIndex":2,"transform":{"x":970,"y":0,"width":130,"height":58},"style":{"fill":{"type":"SOLID","color":"#91a7b1"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":19,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.maidens","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"rr","name":"Runs","type":"TEXT","zIndex":2,"transform":{"x":1130,"y":0,"width":130,"height":58},"style":{"fill":{"type":"SOLID","color":"#91a7b1"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":800,"fontSize":19,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.runs","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"rw","name":"Wickets","type":"TEXT","zIndex":2,"transform":{"x":1290,"y":0,"width":130,"height":58},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"0","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":23,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.wickets","fallback":0,"format":"INTEGER","prefix":"","suffix":""}]},
{"id":"re","name":"Economy","type":"TEXT","zIndex":2,"transform":{"x":1450,"y":0,"width":185,"height":58},"style":{"fill":{"type":"SOLID","color":"#81dbb9"}},"text":{"value":"0.00","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":20,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"item.economy","fallback":0,"format":"DECIMAL_2","prefix":"","suffix":""}]}
]}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"bowling-scorecard","variant":"fullscreen"}}
$json$::jsonb;

when '50.fullscreen' then return public.ips_prism_factory_document_v2('milestone-base') || jsonb_build_object('name','PRISM FIFTY Fullscreen','metadata',jsonb_build_object('factory','IPS PRISM','scene','50','variant','fullscreen'));
when '100.fullscreen' then return jsonb_set(jsonb_set(public.ips_prism_factory_document_v2('milestone-base'),'{name}','"PRISM CENTURY Fullscreen"'::jsonb),'{elements,2,text,value}','"100"'::jsonb);
when 'milestone-base' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM Milestone","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"ms-bg","name":"Milestone Background","type":"RECT","zIndex":1,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{"fill":{"type":"RADIAL_GRADIENT","stops":[{"offset":0,"color":"#174f54"},{"offset":0.55,"color":"#0a2130"},{"offset":1,"color":"#040b12"}]}}},
{"id":"ms-particles","name":"Celebration Particles","type":"PARTICLES","zIndex":2,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{},"effect":{"kind":"PARTICLE_DEPTH","params":{"count":70,"color":"#b4ffe7","depth":0.8}},"animation":{"enterPreset":"IMPACT","durationMs":900,"exitPreset":"FADE","exitDurationMs":250}},
{"id":"ms-num","name":"Milestone Number","type":"TEXT","zIndex":4,"transform":{"x":300,"y":155,"width":720,"height":650,"rotation":-3},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":100,"stops":[{"offset":0,"color":"#ffffff"},{"offset":1,"color":"#19d18f"}]},"glow":16},"text":{"value":"50","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":570,"lineHeight":0.85,"letterSpacing":-35,"align":"CENTER","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"animation":{"enterPreset":"SCALE_POP","durationMs":520,"delayMs":100,"exitPreset":"FADE","exitDurationMs":260}},
{"id":"ms-name","name":"Player Name","type":"TEXT","zIndex":5,"transform":{"x":990,"y":410,"width":650,"height":135},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BATTER","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":70,"lineHeight":0.95,"letterSpacing":-2.5,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":2,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.name","fallback":"BATTER","format":"RAW","prefix":"","suffix":""}]},
{"id":"ms-label","name":"Milestone Label","type":"TEXT","zIndex":5,"transform":{"x":1005,"y":570,"width":620,"height":70},"style":{"fill":{"type":"SOLID","color":"#82ddba"}},"text":{"value":"MILESTONE","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":34,"lineHeight":1,"letterSpacing":5,"align":"LEFT","verticalAlign":"MIDDLE","case":"UPPER","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"ms-score","name":"Innings Score","type":"TEXT","zIndex":5,"transform":{"x":1005,"y":665,"width":600,"height":55},"style":{"fill":{"type":"SOLID","color":"#a8bbc4"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":850,"fontSize":26,"lineHeight":1,"letterSpacing":0,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.score_display","fallback":"","format":"RAW","prefix":"","suffix":""}]},
{"id":"ms-sweep","name":"Milestone Light","type":"EFFECT","zIndex":8,"transform":{"x":0,"y":0,"width":1920,"height":1080},"style":{},"effect":{"kind":"LIGHT_SWEEP","params":{"width":320,"intensity":0.5,"angle":-16}},"animation":{"enterPreset":"LIGHT_SWEEP","durationMs":1200,"delayMs":280,"exitPreset":"FADE","exitDurationMs":100}}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"milestone","variant":"base"}}
$json$::jsonb;

when '50.lower-third' then return $json$
{"schemaVersion":1,"canvas":{"width":1920,"height":1080,"transparent":true},"name":"PRISM FIFTY Lower Third","designTokens":{},"safeArea":{"top":54,"right":96,"bottom":54,"left":96},"elements":[
{"id":"50b","name":"Milestone Bar","type":"ROUNDED_RECT","zIndex":1,"transform":{"x":360,"y":844,"width":1200,"height":132},"style":{"fill":{"type":"LINEAR_GRADIENT","angle":0,"stops":[{"offset":0,"color":"#0b674e"},{"offset":0.5,"color":"#071c2b"},{"offset":1,"color":"#13495d"}]},"corners":{"tl":18,"tr":18,"br":18,"bl":18,"linked":true}},"animation":{"enterPreset":"BROADCAST_WIPE","durationMs":400,"exitPreset":"WIPE","exitDurationMs":280}},
{"id":"50n","name":"Fifty","type":"TEXT","zIndex":3,"transform":{"x":400,"y":858,"width":200,"height":100},"style":{"fill":{"type":"SOLID","color":"#82efc8"}},"text":{"value":"50","typography":{"fontFamily":"Inter","fontWeight":1000,"fontSize":86,"lineHeight":0.9,"letterSpacing":-5,"align":"CENTER","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}}},
{"id":"50p","name":"Batter","type":"TEXT","zIndex":3,"transform":{"x":640,"y":870,"width":650,"height":78},"style":{"fill":{"type":"SOLID","color":"#ffffff"}},"text":{"value":"BATTER","typography":{"fontFamily":"Inter","fontWeight":950,"fontSize":40,"lineHeight":1,"letterSpacing":-1,"align":"LEFT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.name","fallback":"BATTER","format":"RAW","prefix":"","suffix":""}]},
{"id":"50s","name":"Score","type":"TEXT","zIndex":3,"transform":{"x":1280,"y":870,"width":230,"height":78},"style":{"fill":{"type":"SOLID","color":"#a9bbc4"}},"text":{"value":"","typography":{"fontFamily":"Inter","fontWeight":900,"fontSize":28,"lineHeight":1,"letterSpacing":0,"align":"RIGHT","verticalAlign":"MIDDLE","case":"NONE","wrap":"SHRINK","maxLines":1,"padding":0}},"bindings":[{"property":"text.value","path":"current.striker.score_display","fallback":"","format":"RAW","prefix":"","suffix":""}]}
],"guides":[],"metadata":{"factory":"IPS PRISM","scene":"50","variant":"lower-third"}}
$json$::jsonb;

when '100.lower-third' then return jsonb_set(jsonb_set(public.ips_prism_factory_document_v2('50.lower-third'),'{name}','"PRISM CENTURY Lower Third"'::jsonb),'{elements,1,text,value}','"100"'::jsonb);

else raise exception 'Unknown PRISM v2 document %',p_key;
end case;
end
$$;

revoke all on function public.ips_prism_factory_document_v2(text) from public,anon;
grant execute on function public.ips_prism_factory_document_v2(text) to authenticated,service_role;

with pkg as (
 select * from public.broadcast_packages where slug='ips-prism' and is_factory limit 1
),
scene_rows(scene_key,name,category,replacement_group,priority) as (
 values
 ('vs','Match VS','MATCH','fullscreen',80),
 ('batter-info','Batter Info','PLAYER','player-feature',70),
 ('bowler-info','Bowler Info','BOWLER','player-feature',70),
 ('need-from','Need X From X','SITUATION','lower-third',60),
 ('partnership','Current Partnership','SITUATION','lower-third',60),
 ('playing-xi','Playing XI','MATCH','fullscreen',80),
 ('batting-scorecard','Live Batting Scorecard','SCORECARDS','fullscreen',80),
 ('bowling-scorecard','Live Bowling Scorecard','SCORECARDS','fullscreen',80),
 ('50','Fifty','EVENT','event',90),
 ('100','Century','EVENT','event',90)
),
scenes as (
 insert into public.broadcast_scenes(package_id,scene_key,name,category,description,factory_locked,director_visible,director_label,replacement_group,default_priority)
 select pkg.id,r.scene_key,r.name,r.category,'IPS PRISM factory graphic',true,true,upper(r.name),r.replacement_group,r.priority
 from pkg cross join scene_rows r
 on conflict(package_id,scene_key) do update set name=excluded.name,category=excluded.category,factory_locked=true,director_visible=true,replacement_group=excluded.replacement_group,default_priority=excluded.default_priority
 returning id,scene_key
),
variant_rows(scene_key,variant_key,name,presentation,is_default,priority,replacement_group,conflict_behavior,duration_ms,direct_take,automation) as (
 values
 ('vs','fullscreen','PRISM Match VS','FULLSCREEN',true,80,'fullscreen','HIDE_SCOREBAR',7000,false,false),
 ('batter-info','large','PRISM Batter Info','CARD',true,70,'player-feature','COEXIST',5500,false,false),
 ('bowler-info','large','PRISM Bowler Info','CARD',true,70,'player-feature','COEXIST',5500,false,false),
 ('need-from','lower-third','PRISM Need X From X','LOWER_THIRD',true,60,'lower-third','COEXIST',4800,true,false),
 ('partnership','lower-third','PRISM Current Partnership','LOWER_THIRD',true,60,'lower-third','COEXIST',5000,true,false),
 ('playing-xi','home','PRISM Playing XI — Home','FULLSCREEN',true,80,'fullscreen','HIDE_SCOREBAR',10000,false,false),
 ('playing-xi','away','PRISM Playing XI — Away','FULLSCREEN',false,80,'fullscreen','HIDE_SCOREBAR',10000,false,false),
 ('batting-scorecard','fullscreen','PRISM Live Batting Scorecard','FULLSCREEN',true,80,'fullscreen','HIDE_SCOREBAR',10000,false,false),
 ('bowling-scorecard','fullscreen','PRISM Live Bowling Scorecard','FULLSCREEN',true,80,'fullscreen','HIDE_SCOREBAR',10000,false,false),
 ('50','fullscreen','PRISM FIFTY Fullscreen','FULLSCREEN',true,90,'event','HIDE_SCOREBAR',4200,false,true),
 ('50','lower-third','PRISM FIFTY Lower Third','LOWER_THIRD',false,90,'event','COEXIST',3500,false,true),
 ('100','fullscreen','PRISM CENTURY Fullscreen','FULLSCREEN',true,90,'event','HIDE_SCOREBAR',4800,false,true),
 ('100','lower-third','PRISM CENTURY Lower Third','LOWER_THIRD',false,90,'event','COEXIST',4000,false,true)
),
variants as (
 insert into public.broadcast_variants(scene_id,variant_key,name,presentation,is_default,priority,replacement_group,conflict_behavior,default_duration_ms,direct_take,retrigger_policy,automation_eligible)
 select s.id,v.variant_key,v.name,v.presentation,v.is_default,v.priority,v.replacement_group,v.conflict_behavior,v.duration_ms,v.direct_take,'RESTART',v.automation
 from scenes s join variant_rows v using(scene_key)
 on conflict(scene_id,variant_key) do update set name=excluded.name,presentation=excluded.presentation,is_default=excluded.is_default,priority=excluded.priority,replacement_group=excluded.replacement_group,conflict_behavior=excluded.conflict_behavior,default_duration_ms=excluded.default_duration_ms,direct_take=excluded.direct_take,automation_eligible=excluded.automation_eligible
 returning id,scene_id,variant_key
),
published as (
 insert into public.broadcast_variant_versions(variant_id,version_no,status,document,source,published_at)
 select v.id,1,'PUBLISHED',public.ips_prism_factory_document_v2(s.scene_key||'.'||v.variant_key),'FACTORY',now()
 from variants v join scenes s on s.id=v.scene_id
 on conflict(variant_id,version_no) do update set document=excluded.document,status='PUBLISHED',source='FACTORY',published_at=now()
 returning id
),
release_no as (
 select coalesce(max(r.version_no),0)+1 version_no from public.broadcast_package_releases r join pkg on pkg.id=r.package_id
)
insert into public.broadcast_package_releases(package_id,version_no,manifest,theme,checksum)
select pkg.id,release_no.version_no,public.ips_broadcast_build_release_manifest(pkg.id),pkg.theme,'ips-prism-factory-2'
from pkg cross join release_no;

commit;
