export const dynamic='force-dynamic'; export const revalidate=0;
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteFooter,SiteHeader} from '@/components/site-header';
import {ManagementNav} from '@/components/manage/manage-nav';
import {requireAccount} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {Crest} from '@/components/identity';
import {removeEntityImage,updateClub,uploadEntityImage} from '../../registry/actions';

export default async function ClubOperationsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const account=await requireAccount(); const {id}=await params; const sp=await searchParams; const error=typeof sp.error==='string'?sp.error:null; const ok=typeof sp.ok==='string'?sp.ok:null; const supabase=await createClient();
 const {data:club}=await supabase.from('clubs').select('*,city:cities(id,name)').eq('id',id).maybeSingle(); if(!club)notFound();
 const [{data:teams},{data:members},perm]=await Promise.all([supabase.from('teams').select('id,name,short_name,category,logo_url,status').eq('club_id',id).order('name'),supabase.from('team_memberships').select('id,team_id').eq('status','ACTIVE').is('end_on',null),supabase.rpc('ips_can_manage_club',{p_club_id:id})]);
 const canManage=!!perm.data; const memberCount=new Map<string,number>(); for(const m of members??[])memberCount.set(m.team_id,(memberCount.get(m.team_id)||0)+1);
 return <main className="shell sports-shell"><SiteHeader/><ManagementNav account={account} active="clubs"/><section className="entity-command-header"><div className="entity-brand"><Crest name={club.name} imageUrl={club.logo_url} large/><div><Link className="back-link" href="/manage/clubs">← Clubs</Link><span className="eyebrow">CLUB OPERATIONS · {(club.city as any)?.name}</span><h1>{club.name}</h1><p>{club.description||'Canonical club identity in IPS.'}</p></div></div>{canManage&&<Link className="button-primary" href={`/manage/clubs/${id}/teams/new`}>+ Add team</Link>}</section>
 {(error||ok)&&<div className={`ops-message ${error?'error':'success'}`}>{error||ok}</div>}
 <section className="ops-kpi-strip"><article><span>Teams</span><strong>{teams?.length??0}</strong><small>registered</small></article><article><span>Players</span><strong>{members?.length??0}</strong><small>active memberships</small></article><article><span>Status</span><strong>{club.status}</strong><small>club identity</small></article><article><span>Verification</span><strong>{club.verified?'YES':'—'}</strong><small>IPS verified</small></article></section>
 <section className="entity-layout"><div className="management-surface"><div className="surface-head"><div><span className="eyebrow">TEAMS</span><h2>Club teams</h2></div></div><div className="team-list">{(teams??[]).map((t:any)=><Link href={`/manage/teams/${t.id}`} className="team-list-row" key={t.id}><Crest name={t.name} imageUrl={t.logo_url}/><div><h3>{t.name}</h3><p>{t.category} · {memberCount.get(t.id)||0} active players</p></div><span>Manage roster →</span></Link>)}</div>{!teams?.length&&<div className="sports-empty"><strong>No teams yet.</strong><p>Add the first team under this club.</p></div>}</div>
 {canManage&&<aside className="management-stack"><section className="management-surface"><div className="surface-head"><div><span className="eyebrow">CLUB DETAILS</span><h2>Identity</h2></div></div><form action={updateClub} className="compact-form"><input type="hidden" name="club_id" value={id}/><input type="hidden" name="return_to" value={`/manage/clubs/${id}`}/><label><span>Name</span><input name="name" defaultValue={club.name}/></label><label><span>Short name</span><input name="short_name" defaultValue={club.short_name??''}/></label><div className="form-split"><label><span>Founded</span><input name="founded_year" type="number" defaultValue={club.founded_year??''}/></label><label><span>Website</span><input name="website_url" type="url" defaultValue={club.website_url??''}/></label></div><label><span>Description</span><textarea name="description" rows={3} defaultValue={club.description??''}/></label><button>Save club details</button></form></section><section className="management-surface"><div className="surface-head"><div><span className="eyebrow">CLUB CREST</span><h2>Logo</h2></div></div><form action={uploadEntityImage} className="media-form" encType="multipart/form-data"><input type="hidden" name="kind" value="clubs"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/clubs/${id}`}/><input type="file" name="image" accept="image/jpeg,image/png,image/webp" required/><button>Upload / replace</button></form>{club.logo_url&&<form action={removeEntityImage}><input type="hidden" name="kind" value="clubs"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/clubs/${id}`}/><button className="danger-link">Remove logo</button></form>}</section></aside>}
 </section><SiteFooter/></main>;
}
