export const dynamic='force-dynamic'; export const revalidate=0;
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteFooter,SiteHeader} from '@/components/site-header';
import {ManagementNav} from '@/components/manage/manage-nav';
import {requireAccount} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {Crest,PlayerAvatar} from '@/components/identity';
import {ConfirmSubmitButton} from '@/components/manage/confirm-submit-button';
import {deleteTeam,endMembership,removeEntityImage,updateMembership,updateTeam,uploadEntityImage} from '../../registry/actions';

export default async function TeamOperationsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const account=await requireAccount(); const {id}=await params; const sp=await searchParams; const error=typeof sp.error==='string'?sp.error:null; const ok=typeof sp.ok==='string'?sp.ok:null; const supabase=await createClient();
 const {data:team}=await supabase.from('teams').select('*,club:clubs(id,name,logo_url,city:cities(name))').eq('id',id).maybeSingle(); if(!team)notFound();
 const [{data:members},perm]=await Promise.all([supabase.from('team_memberships').select('id,player_id,shirt_number,is_primary,start_on,player:players(id,ips_code,display_name,primary_role,profile_image_url)').eq('team_id',id).eq('status','ACTIVE').is('end_on',null).order('start_on'),supabase.rpc('ips_can_manage_team',{p_team_id:id})]);
 const canManage=!!perm.data; const canGlobalDelete=account.grants.some(g=>(g.role==='OWNER'&&g.scope_type==='GLOBAL')||(g.role==='ADMIN'&&g.scope_type==='GLOBAL')); const playerIds=(members??[]).map((m:any)=>m.player_id); let contacts:any[]=[]; if(playerIds.length){const r=await supabase.from('player_contacts').select('player_id,contact_type,value_normalized,notification_consent,verified_at').in('player_id',playerIds);contacts=r.data??[];}
 const contactsByPlayer=new Map<string,any[]>(); for(const c of contacts){if(!contactsByPlayer.has(c.player_id))contactsByPlayer.set(c.player_id,[]);contactsByPlayer.get(c.player_id)!.push(c);}
 return <main className="shell sports-shell"><SiteHeader/><ManagementNav account={account} active="teams"/><section className="entity-command-header"><div className="entity-brand"><Crest name={team.name} imageUrl={team.logo_url} large/><div><Link className="back-link" href="/manage/teams">← Teams</Link><span className="eyebrow">TEAM OPERATIONS · {(team.club as any)?.city?.name??'ITALY'}</span><h1>{team.name}</h1><p>{(team.club as any)?.name} · {team.category}</p></div></div><div className="header-actions">{canManage&&<><a href="#team-details" className="button-secondary">Edit team</a><Link href={`/manage/teams/${id}/players/add`} className="button-primary">+ Add player</Link></>}{canGlobalDelete&&<form action={deleteTeam}><input type="hidden" name="team_id" value={id}/><ConfirmSubmitButton className="danger-link" message={`Delete ${team.name}? This permanently removes the team and its roster memberships. Players themselves are not deleted. Teams already used in tournaments or matches are protected and cannot be deleted.`}>Delete team</ConfirmSubmitButton></form>}</div></section>
 {(error||ok)&&<div className={`ops-message ${error?'error':'success'}`}>{error||ok}</div>}
 <section className="ops-kpi-strip"><article><span>Active roster</span><strong>{members?.length??0}</strong><small>players</small></article><article><span>Primary</span><strong>{(members??[]).filter((m:any)=>m.is_primary).length}</strong><small>memberships</small></article><article><span>Contacts</span><strong>{contacts.filter(c=>c.contact_type==='PHONE').length}</strong><small>phone / WhatsApp</small></article><article><span>Status</span><strong>{team.status}</strong><small>team record</small></article></section>
 <section className="entity-layout team-ops-layout"><div className="management-surface"><div className="surface-head"><div><span className="eyebrow">ACTIVE ROSTER</span><h2>Players</h2></div><span>Permanent IPS identities</span></div><div className="roster-table">{(members??[]).map((m:any)=>{const p=m.player;const pcs=contactsByPlayer.get(m.player_id)??[];const phone=pcs.find(c=>c.contact_type==='PHONE');const email=pcs.find(c=>c.contact_type==='EMAIL');return <article className="roster-row" key={m.id}><PlayerAvatar name={p?.display_name??'Player'} imageUrl={p?.profile_image_url}/><div className="roster-player"><Link href={`/manage/players/${p.id}`}>{p.display_name}</Link><span>{p.ips_code} · {p.primary_role||'Player'}</span><small>{email?.value_normalized||'No email'}{phone?` · ${phone.value_normalized}`:''}</small></div><div className="roster-shirt"><span>SHIRT</span><b>{m.shirt_number??'—'}</b></div>{canManage&&<div className="roster-actions"><form action={updateMembership}><input type="hidden" name="membership_id" value={m.id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}`}/><input name="shirt_number" type="number" min="0" max="999" defaultValue={m.shirt_number??''} placeholder="#"/><button>Save</button></form><form action={endMembership}><input type="hidden" name="membership_id" value={m.id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}`}/><button className="danger-link">Remove</button></form></div>}</article>})}</div>{!members?.length&&<div className="sports-empty"><strong>No active players.</strong><p>Add an existing IPS player or register a new one.</p></div>}</div>
 {canManage&&<aside className="management-stack"><section id="team-details" className="management-surface"><div className="surface-head"><div><span className="eyebrow">TEAM DETAILS</span><h2>Identity</h2></div><span>{canGlobalDelete?'Global management':'Scoped team management'}</span></div><form action={updateTeam} className="compact-form"><input type="hidden" name="team_id" value={id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}`}/><label><span>Name</span><input name="name" defaultValue={team.name}/></label><label><span>Short name</span><input name="short_name" defaultValue={team.short_name??''}/></label><label><span>Category</span><select name="category" defaultValue={team.category}><option value="OPEN">Open</option><option value="MEN">Men</option><option value="WOMEN">Women</option><option value="YOUTH">Youth</option><option value="SOCIAL">Social</option></select></label><button>Save team details</button></form></section><section className="management-surface"><div className="surface-head"><div><span className="eyebrow">TEAM CREST</span><h2>Logo</h2></div></div><form action={uploadEntityImage} className="media-form" encType="multipart/form-data"><input type="hidden" name="kind" value="teams"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}`}/><input type="file" name="image" accept="image/jpeg,image/png,image/webp" required/><button>Upload / replace</button></form>{team.logo_url&&<form action={removeEntityImage}><input type="hidden" name="kind" value="teams"/><input type="hidden" name="entity_id" value={id}/><input type="hidden" name="return_to" value={`/manage/teams/${id}`}/><button className="danger-link">Remove logo</button></form>}</section></aside>}
 </section><SiteFooter/></main>;
}
